export const products = [
    // QOZONLAR (5 товаров)
    {
        id: 1,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Katta Qozon 10L',
        price: 350000,
        newPrice: 299000,
        discount: true,
        category: 'QOZONLAR',
        rating: { rate: 4.5, count: 120 },
        shortDesc: 'Sifatli alyuminiy qozon, katta oilalar uchun.',
        fullDesc: '10 litrli qozon tez qiziydi, issiqlikni yaxshi saqlaydi va chidamli.',
        weight: '3kg',
        color: 'kumush',
        type: 'alyuminiy',
        qty: 50,
        tages: 'qozon, oshxona, katta',
        brandImg: '/images/brands/brand1.png',
        comments: [
            { clientName: 'Ali', clientComment: 'Zo‘r qozon, palov ajoyib chiqdi!', clientRate: 5 },
        ],
        sku: 'QZN-001',
    },
    {
        id: 2,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'O‘rta Qozon 7L',
        price: 280000,
        newPrice: 280000,
        discount: false,
        category: 'QOZONLAR',
        rating: { rate: 4.2, count: 85 },
        shortDesc: 'O‘rta oila uchun ideal qozon.',
        fullDesc: '7 litrli qozon, energiya tejash xususiyati bilan.',
        weight: '2.5kg',
        color: 'qizil',
        type: 'po‘lat',
        qty: 70,
        tages: 'qozon, o‘rta, oshxona',
        brandImg: '/images/brands/brand1.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Qozon yaxshi, lekin biroz og‘ir.', clientRate: 4 },
        ],
        sku: 'QZN-002',
    },
    {
        id: 3,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kichik Qozon 5L',
        price: 220000,
        newPrice: 200000,
        discount: true,
        category: 'QOZONLAR',
        rating: { rate: 4.0, count: 60 },
        shortDesc: 'Yakkaxon oshxonalar uchun mos.',
        fullDesc: '5 litrli qozon kichik oilalar va yakka shaxslar uchun ideal.',
        weight: '2kg',
        color: 'ko‘k',
        type: 'temir',
        qty: 40,
        tages: 'qozon, kichik, tejamkor',
        brandImg: '/images/brands/brand1.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Kichik lekin sifatli, tavsiya etaman.', clientRate: 4 },
        ],
        sku: 'QZN-003',
    },
    {
        id: 4,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Premium Qozon 12L',
        price: 500000,
        newPrice: 450000,
        discount: true,
        category: 'QOZONLAR',
        rating: { rate: 4.8, count: 150 },
        shortDesc: 'Yuqori sifatli, premium toifadagi qozon.',
        fullDesc: '12 litrli premium qozon, yuqori issiqlik tarqatuvchi texnologiya bilan.',
        weight: '4kg',
        color: 'oltin',
        type: 'keramika qoplamali',
        qty: 30,
        tages: 'qozon, premium, oshxona',
        brandImg: '/images/brands/brand1.png',
        comments: [
            { clientName: 'Jasur', clientComment: 'Haqiqatan ham ajoyib, har qanday taomga mos.', clientRate: 5 },
        ],
        sku: 'QZN-004',
    },
    {
        id: 5,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Econom Qozon 8L',
        price: 260000,
        newPrice: 260000,
        discount: false,
        category: 'QOZONLAR',
        rating: { rate: 3.8, count: 40 },
        shortDesc: 'Arzon va ishonchli variant.',
        fullDesc: '8 litrli ekonom variant, kundalik pishirish uchun etarli.',
        weight: '2.8kg',
        color: 'kulrang',
        type: 'po‘lat',
        qty: 60,
        tages: 'qozon, econom, oshxona',
        brandImg: '/images/brands/brand1.png',
        comments: [
            { clientName: 'Dilshod', clientComment: 'Bajaradi, lekin yuqori darajada emas.', clientRate: 3 },
        ],
        sku: 'QZN-005',
    },
    // SKAVAROTKALAR (5 товаров)
    {
        id: 6,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Teflon Skavarka',
        price: 210000,
        newPrice: 190000,
        discount: true,
        category: 'SKAVAROTKALAR',
        rating: { rate: 4.1, count: 76 },
        shortDesc: 'Yopishmaydigan, nonushta uchun ideal skavarka.',
        fullDesc: 'Teflon qoplama, ergonomik dizayn, gaz va elektr plitalarga mos.',
        weight: '1.5kg',
        color: 'qora',
        type: 'teflon',
        qty: 30,
        tages: 'skavarka, oshxona, teflon',
        brandImg: '/images/brands/brand2.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Tuxum yopishmaydi, juda yoqdi!', clientRate: 4 },
        ],
        sku: 'SKV-001',
    },
    {
        id: 7,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Anti-stick Skavarka',
        price: 230000,
        newPrice: 230000,
        discount: false,
        category: 'SKAVAROTKALAR',
        rating: { rate: 4.3, count: 90 },
        shortDesc: 'Silliq va bardoshli skavarka.',
        fullDesc: 'Yuqori sifatli qoplama bilan qozon bo‘ylab teng taqsimlanadi, pishirish oson.',
        weight: '1.7kg',
        color: 'qizil',
        type: 'non-stick',
        qty: 25,
        tages: 'skavarka, oshxona, anti-stick',
        brandImg: '/images/brands/brand2.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Pishirish paytida qo‘l keladi.', clientRate: 4 },
        ],
        sku: 'SKV-002',
    },
    {
        id: 8,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Skavarka Pro',
        price: 250000,
        newPrice: 225000,
        discount: true,
        category: 'SKAVAROTKALAR',
        rating: { rate: 4.6, count: 110 },
        shortDesc: 'Professional darajadagi skavarka.',
        fullDesc: 'Tez isinish, yuqori pishirish samaradorligi va ergonomik dizayn.',
        weight: '1.6kg',
        color: 'yashil',
        type: 'pro qoplama',
        qty: 20,
        tages: 'skavarka, pro, oshxona',
        brandImg: '/images/brands/brand2.png',
        comments: [
            { clientName: 'Jasur', clientComment: 'Haqiqiy pro mahsulot, tavsiya qilaman.', clientRate: 5 },
        ],
        sku: 'SKV-003',
    },
    {
        id: 9,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Mini Skavarka',
        price: 180000,
        newPrice: 180000,
        discount: false,
        category: 'SKAVAROTKALAR',
        rating: { rate: 3.9, count: 55 },
        shortDesc: 'Kichik oshxonalar uchun.',
        fullDesc: 'Kompakt dizayn, oson saqlash va qulay foydalanish uchun yaratilgan.',
        weight: '1.2kg',
        color: 'kulrang',
        type: 'kompakt',
        qty: 35,
        tages: 'skavarka, kichik, oshxona',
        brandImg: '/images/brands/brand2.png',
        comments: [
            { clientName: 'Dilshod', clientComment: 'Oddiy, lekin ishonchli.', clientRate: 4 },
        ],
        sku: 'SKV-004',
    },
    {
        id: 10,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Skavarka Plus',
        price: 240000,
        newPrice: 240000,
        discount: false,
        category: 'SKAVAROTKALAR',
        rating: { rate: 4.0, count: 65 },
        shortDesc: 'Yuqori texnologiyali skavarka.',
        fullDesc: 'Innovatsion dizayn va mustahkam qoplama bilan ta’minlangan.',
        weight: '1.8kg',
        color: 'ko‘k',
        type: 'plus qoplama',
        qty: 28,
        tages: 'skavarka, plus, oshxona',
        brandImg: '/images/brands/brand2.png',
        comments: [
            { clientName: 'Ali', clientComment: 'Samarali ishlaydi, ozgina qimmat.', clientRate: 4 },
        ],
        sku: 'SKV-005',
    },
    // PICHOQLAR (5 товаров)
    {
        id: 11,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Pichoq To‘plami 5 dona',
        price: 120000,
        newPrice: 120000,
        discount: false,
        category: 'PICHOQLAR',
        rating: { rate: 4.8, count: 230 },
        shortDesc: 'Zanglamaydigan po‘lat pichoq to‘plami.',
        fullDesc: 'To‘plamga turli o‘lchamdagi, keskin pichoq va qulay tutqichli asboblar kiradi.',
        weight: '1kg',
        color: 'kumush',
        type: 'po‘lat',
        qty: 100,
        tages: 'pichoq, oshxona, to‘plam',
        brandImg: '/images/brands/brand3.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Sifatli, sabzavotlarni osongina kesadi.', clientRate: 5 },
        ],
        sku: 'PCH-001',
    },
    {
        id: 12,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Professional Pichoq',
        price: 90000,
        newPrice: 80000,
        discount: true,
        category: 'PICHOQLAR',
        rating: { rate: 4.3, count: 150 },
        shortDesc: 'Yagona professional pichoq.',
        fullDesc: 'Yuqori sifatli po‘lat, oshxonada aniqlik va samaradorlikni ta’minlaydi.',
        weight: '0.3kg',
        color: 'qora',
        type: 'professional',
        qty: 80,
        tages: 'pichoq, professional, oshxona',
        brandImg: '/images/brands/brand3.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Kichik, lekin juda keskin.', clientRate: 4 },
        ],
        sku: 'PCH-002',
    },
    {
        id: 13,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Multi Pichoq Set',
        price: 150000,
        newPrice: 150000,
        discount: false,
        category: 'PICHOQLAR',
        rating: { rate: 4.7, count: 180 },
        shortDesc: 'Setda turli o‘lchamdagi pichoqlar.',
        fullDesc: 'Har bir oshpaz uchun zarur bo‘lgan, turli vazifalar uchun mos pichoq seti.',
        weight: '1.2kg',
        color: 'kumush',
        type: 'multi-set',
        qty: 90,
        tages: 'pichoq, set, oshxona',
        brandImg: '/images/brands/brand3.png',
        comments: [
            { clientName: 'Jasur', clientComment: 'Ajoyib set, har bir taom uchun yetarli.', clientRate: 5 },
        ],
        sku: 'PCH-003',
    },
    {
        id: 14,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Yengil Pichoq',
        price: 70000,
        newPrice: 70000,
        discount: false,
        category: 'PICHOQLAR',
        rating: { rate: 4.0, count: 95 },
        shortDesc: 'Yengil va oson ushlanadigan pichoq.',
        fullDesc: 'Oson boshqariladigan va keskin pichoq, kundalik ishlarda ideal variant.',
        weight: '0.25kg',
        color: 'qizil',
        type: 'yengil',
        qty: 120,
        tages: 'pichoq, yengil, oshxona',
        brandImg: '/images/brands/brand3.png',
        comments: [
            { clientName: 'Ali', clientComment: 'Kichkina lekin ishni yaxshi bajaradi.', clientRate: 4 },
        ],
        sku: 'PCH-004',
    },
    {
        id: 15,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Pichoq Set Elite',
        price: 200000,
        newPrice: 180000,
        discount: true,
        category: 'PICHOQLAR',
        rating: { rate: 4.9, count: 210 },
        shortDesc: 'Elite pichoq to‘plami yuqori darajadagi sifat bilan.',
        fullDesc: 'Zanglamaydigan, ergonomik tutqichli va uzoq muddat xizmat qiladigan mahsulot.',
        weight: '1.3kg',
        color: 'qora',
        type: 'elite',
        qty: 70,
        tages: 'pichoq, elite, oshxona',
        brandImg: '/images/brands/brand3.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Haqiqiy elite sifat, tavsiya etaman!', clientRate: 5 },
        ],
        sku: 'PCH-005',
    },
    // OSHXONA NABORLAR (5 товаров)
    {
        id: 16,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Oshxona Nabor 1',
        price: 300000,
        newPrice: 270000,
        discount: true,
        category: 'OSHXONA NABORLAR',
        rating: { rate: 4.4, count: 130 },
        shortDesc: 'To‘liq oshxona nabori, barcha kerakli asboblar bilan.',
        fullDesc: 'Naborga qozon, skavarka, pichoq va boshqa oshxona anjomlari kiradi.',
        weight: '5kg',
        color: 'ko‘k',
        type: 'komplekt',
        qty: 40,
        tages: 'nabor, oshxona, komplekt',
        brandImg: '/images/brands/brand4.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Barcha kerakli narsalar bor, juda ma’qul.', clientRate: 5 },
        ],
        sku: 'OSN-001',
    },
    {
        id: 17,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Oshxona Nabor 2',
        price: 320000,
        newPrice: 320000,
        discount: false,
        category: 'OSHXONA NABORLAR',
        rating: { rate: 4.1, count: 110 },
        shortDesc: 'Praktik va bardoshli oshxona nabori.',
        fullDesc: 'Barcha asosiy oshxona anjomlari bitta to‘plamda.',
        weight: '5.5kg',
        color: 'qizil',
        type: 'standart',
        qty: 35,
        tages: 'nabor, oshxona, standart',
        brandImg: '/images/brands/brand4.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Ishlatish oson, lekin tanasi biroz og‘ir.', clientRate: 4 },
        ],
        sku: 'OSN-002',
    },
    {
        id: 18,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Oshxona Nabor Deluxe',
        price: 450000,
        newPrice: 400000,
        discount: true,
        category: 'OSHXONA NABORLAR',
        rating: { rate: 4.7, count: 90 },
        shortDesc: 'Deluxe toifadagi oshxona nabori.',
        fullDesc: 'Yuqori sifatli materiallardan tayyorlangan va zamonaviy dizaynga ega.',
        weight: '6kg',
        color: 'oltin',
        type: 'deluxe',
        qty: 25,
        tages: 'nabor, deluxe, oshxona',
        brandImg: '/images/brands/brand4.png',
        comments: [
            { clientName: 'Jasur', clientComment: 'Haqiqatan ham ajoyib, premium his-tuyg‘u beradi.', clientRate: 5 },
        ],
        sku: 'OSN-003',
    },
    {
        id: 19,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Oshxona Nabor Basic',
        price: 250000,
        newPrice: 250000,
        discount: false,
        category: 'OSHXONA NABORLAR',
        rating: { rate: 3.9, count: 70 },
        shortDesc: 'Asosiy oshxona anjomlari to‘plami.',
        fullDesc: 'Sodda, lekin kerakli barcha asboblarni o‘z ichiga oladi.',
        weight: '4.8kg',
        color: 'yashil',
        type: 'basic',
        qty: 45,
        tages: 'nabor, basic, oshxona',
        brandImg: '/images/brands/brand4.png',
        comments: [
            { clientName: 'Ali', clientComment: 'Bajaradi, lekin ko‘p funksiyali emas.', clientRate: 3 },
        ],
        sku: 'OSN-004',
    },
    {
        id: 20,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Oshxona Nabor Premium',
        price: 480000,
        newPrice: 460000,
        discount: true,
        category: 'OSHXONA NABORLAR',
        rating: { rate: 4.5, count: 95 },
        shortDesc: 'Premium tanlov uchun oshxona nabori.',
        fullDesc: 'Zamonaviy dizayn va yuqori texnologiyali materiallardan ishlab chiqarilgan.',
        weight: '5.2kg',
        color: 'ko‘k',
        type: 'premium',
        qty: 38,
        tages: 'nabor, premium, oshxona',
        brandImg: '/images/brands/brand4.png',
        comments: [
            { clientName: 'Dilshod', clientComment: 'Narxi yuqori, lekin sifatini his etasiz.', clientRate: 4 },
        ],
        sku: 'OSN-005',
    },
    // QOSHIQLAR (5 товаров)
    {
        id: 21,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Qoshiq Set 3 dona',
        price: 80000,
        newPrice: 80000,
        discount: false,
        category: 'QOSHIQLAR',
        rating: { rate: 4.0, count: 55 },
        shortDesc: 'Kichik qoshiq to‘plami.',
        fullDesc: '3 dona qoshiq: choy, kofe va desert qoshiq.',
        weight: '0.5kg',
        color: 'oq',
        type: 'plastik',
        qty: 100,
        tages: 'qoshiq, to‘plam, oshxona',
        brandImg: '/images/brands/brand5.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Kichik va qulay, kundalik foydalanish uchun.', clientRate: 4 },
        ],
        sku: 'QSH-001',
    },
    {
        id: 22,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Qoshiq Metal 1 dona',
        price: 50000,
        newPrice: 45000,
        discount: true,
        category: 'QOSHIQLAR',
        rating: { rate: 3.8, count: 40 },
        shortDesc: 'Yagona metall qoshiq.',
        fullDesc: 'Sodda dizayn, bardoshli va uzoq umrli.',
        weight: '0.3kg',
        color: 'kulrang',
        type: 'metal',
        qty: 120,
        tages: 'qoshiq, metal, oshxona',
        brandImg: '/images/brands/brand5.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Kichik lekin sifatli.', clientRate: 4 },
        ],
        sku: 'QSH-002',
    },
    {
        id: 23,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Qoshiq Set Deluxe',
        price: 120000,
        newPrice: 110000,
        discount: true,
        category: 'QOSHIQLAR',
        rating: { rate: 4.4, count: 60 },
        shortDesc: 'Deluxe toifadagi qoshiq to‘plami.',
        fullDesc: 'Zamonaviy dizayn va yuqori sifatli materiallardan tayyorlangan.',
        weight: '0.7kg',
        color: 'qora',
        type: 'deluxe',
        qty: 80,
        tages: 'qoshiq, deluxe, oshxona',
        brandImg: '/images/brands/brand5.png',
        comments: [
            { clientName: 'Jasur', clientComment: 'Zamonaviy ko‘rinish, tavsiya qilaman.', clientRate: 5 },
        ],
        sku: 'QSH-003',
    },
    {
        id: 24,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Ergonomic Qoshiq',
        price: 60000,
        newPrice: 60000,
        discount: false,
        category: 'QOSHIQLAR',
        rating: { rate: 4.1, count: 50 },
        shortDesc: 'Ergonomik dizaynga ega qoshiq.',
        fullDesc: 'Qo‘lga qulay tushadigan va zamonaviy uslubdagi qoshiq.',
        weight: '0.4kg',
        color: 'oq',
        type: 'ergonomic',
        qty: 95,
        tages: 'qoshiq, ergonomic, oshxona',
        brandImg: '/images/brands/brand5.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Oddiy lekin yaxshi ishlaydi.', clientRate: 4 },
        ],
        sku: 'QSH-004',
    },
    {
        id: 25,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Qoshiq Set Standard',
        price: 90000,
        newPrice: 90000,
        discount: false,
        category: 'QOSHIQLAR',
        rating: { rate: 3.9, count: 45 },
        shortDesc: 'Standart qoshiq to‘plami.',
        fullDesc: 'Kundalik foydalanish uchun yetarli, hamyonbop variant.',
        weight: '0.6kg',
        color: 'kulrang',
        type: 'standard',
        qty: 110,
        tages: 'qoshiq, standard, oshxona',
        brandImg: '/images/brands/brand5.png',
        comments: [
            { clientName: 'Dilshod', clientComment: 'Narxi yaxshi, ishlashida farq yo‘q.', clientRate: 4 },
        ],
        sku: 'QSH-005',
    },
    // QOZON NABORLAR (5 товаров)
    {
        id: 26,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Qozon Nabor 1',
        price: 400000,
        newPrice: 380000,
        discount: true,
        category: 'QOZON NABORLAR',
        rating: { rate: 4.3, count: 80 },
        shortDesc: 'Qozon va qo‘shimcha asboblar nabori.',
        fullDesc: 'Naborga katta va kichik qozonlar, qopqoqlar ham kiritilgan.',
        weight: '6kg',
        color: 'kumush',
        type: 'komplekt',
        qty: 35,
        tages: 'qozon nabor, oshxona',
        brandImg: '/images/brands/brand6.png',
        comments: [
            { clientName: 'Ali', clientComment: 'Barcha kerakli narsalar bor, buni sotib oling.', clientRate: 5 },
        ],
        sku: 'QZNB-001',
    },
    {
        id: 27,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Qozon Nabor 2',
        price: 420000,
        newPrice: 420000,
        discount: false,
        category: 'QOZON NABORLAR',
        rating: { rate: 4.0, count: 70 },
        shortDesc: 'Standart qozon nabori.',
        fullDesc: 'Asosiy oshxona asboblari to‘plami, kundalik foydalanish uchun.',
        weight: '5.8kg',
        color: 'qizil',
        type: 'standart',
        qty: 40,
        tages: 'qozon nabor, standart, oshxona',
        brandImg: '/images/brands/brand6.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Ishlatishda hech qanday muammo yo‘q.', clientRate: 4 },
        ],
        sku: 'QZNB-002',
    },
    {
        id: 28,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Qozon Nabor Deluxe',
        price: 500000,
        newPrice: 460000,
        discount: true,
        category: 'QOZON NABORLAR',
        rating: { rate: 4.6, count: 95 },
        shortDesc: 'Deluxe qozon nabori yuqori sifat bilan.',
        fullDesc: 'Yuqori sifatli materiallardan tayyorlangan va innovatsion dizaynga ega.',
        weight: '6.5kg',
        color: 'oltin',
        type: 'deluxe',
        qty: 30,
        tages: 'qozon nabor, deluxe, oshxona',
        brandImg: '/images/brands/brand6.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Narxi yuqori, lekin sifati o‘ziga xos.', clientRate: 5 },
        ],
        sku: 'QZNB-003',
    },
    {
        id: 29,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Qozon Nabor Basic',
        price: 380000,
        newPrice: 380000,
        discount: false,
        category: 'QOZON NABORLAR',
        rating: { rate: 3.8, count: 60 },
        shortDesc: 'Asosiy qozon nabori.',
        fullDesc: 'Kundalik foydalanish uchun yetarli bo‘lgan qozon va aksessuarlar.',
        weight: '5.5kg',
        color: 'kulrang',
        type: 'basic',
        qty: 45,
        tages: 'qozon nabor, basic, oshxona',
        brandImg: '/images/brands/brand6.png',
        comments: [
            { clientName: 'Jasur', clientComment: 'Oddiy, lekin buni sinab ko‘ring.', clientRate: 4 },
        ],
        sku: 'QZNB-004',
    },
    {
        id: 30,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Qozon Nabor Pro',
        price: 540000,
        newPrice: 540000,
        discount: false,
        category: 'QOZON NABORLAR',
        rating: { rate: 4.2, count: 75 },
        shortDesc: 'Professional qozon nabori.',
        fullDesc: 'Kuchli va bardoshli, professional oshpazlar uchun mo‘ljallangan.',
        weight: '6kg',
        color: 'ko‘k',
        type: 'pro',
        qty: 33,
        tages: 'qozon nabor, pro, oshxona',
        brandImg: '/images/brands/brand6.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Samarali, uzoq muddat xizmat qiladi.', clientRate: 4 },
        ],
        sku: 'QZNB-005',
    },
    // KASTRULKALAR (5 товаров)
    {
        id: 31,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kastrulka 16cm',
        price: 150000,
        newPrice: 135000,
        discount: true,
        category: 'KASTRULKALAR',
        rating: { rate: 4.2, count: 65 },
        shortDesc: 'Kichik kastrulka kundalik pishirish uchun.',
        fullDesc: '16 sm diametrli, tez isiydi va energiya tejaydi.',
        weight: '0.8kg',
        color: 'qizil',
        type: 'po‘lat',
        qty: 80,
        tages: 'kastrulka, oshxona, kichik',
        brandImg: '/images/brands/brand7.png',
        comments: [
            { clientName: 'Ali', clientComment: 'Kichkina lekin samarali.', clientRate: 4 },
        ],
        sku: 'KST-001',
    },
    {
        id: 32,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kastrulka 20cm',
        price: 190000,
        newPrice: 190000,
        discount: false,
        category: 'KASTRULKALAR',
        rating: { rate: 4.4, count: 80 },
        shortDesc: 'O‘rta oila uchun kastrulka.',
        fullDesc: '20 sm diametrli, keng yuzali va chidamli.',
        weight: '1kg',
        color: 'ko‘k',
        type: 'temir',
        qty: 70,
        tages: 'kastrulka, oshxona, o‘rta',
        brandImg: '/images/brands/brand7.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Pishirishda ishonchli yordamchi.', clientRate: 5 },
        ],
        sku: 'KST-002',
    },
    {
        id: 33,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kastrulka Premium',
        price: 250000,
        newPrice: 225000,
        discount: true,
        category: 'KASTRULKALAR',
        rating: { rate: 4.7, count: 90 },
        shortDesc: 'Premium kastrulka yuqori sifat bilan.',
        fullDesc: 'Zamonaviy texnologiya va yuqori sifatli materiallardan tayyorlangan.',
        weight: '1.2kg',
        color: 'oltin',
        type: 'keramika qoplamali',
        qty: 50,
        tages: 'kastrulka, premium, oshxona',
        brandImg: '/images/brands/brand7.png',
        comments: [
            { clientName: 'Jasur', clientComment: 'Ajoyib kastrulka, tez qiziydi.', clientRate: 5 },
        ],
        sku: 'KST-003',
    },
    {
        id: 34,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kastrulka Econom',
        price: 140000,
        newPrice: 140000,
        discount: false,
        category: 'KASTRULKALAR',
        rating: { rate: 3.9, count: 55 },
        shortDesc: 'Buxgalteriya uchun arzon variant.',
        fullDesc: 'Sodda dizayn, kundalik pishirish uchun yetarli.',
        weight: '0.9kg',
        color: 'kulrang',
        type: 'econom',
        qty: 85,
        tages: 'kastrulka, econom, oshxona',
        brandImg: '/images/brands/brand7.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Narxi arzon, lekin sifat oddiy.', clientRate: 3 },
        ],
        sku: 'KST-004',
    },
    {
        id: 35,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kastrulka Set',
        price: 300000,
        newPrice: 300000,
        discount: false,
        category: 'KASTRULKALAR',
        rating: { rate: 4.5, count: 75 },
        shortDesc: 'To‘plamda kichik va o‘rta kastrulkalar.',
        fullDesc: 'Turli o‘lchamlardagi kastrulkalar seti, oshxonani to‘liq ta’minlaydi.',
        weight: '2kg',
        color: 'qora',
        type: 'set',
        qty: 60,
        tages: 'kastrulka, set, oshxona',
        brandImg: '/images/brands/brand7.png',
        comments: [
            { clientName: 'Madina', clientComment: 'To‘liq to‘plam, har xil ehtiyojlarga mos.', clientRate: 5 },
        ],
        sku: 'KST-005',
    },
    // KASTRULKA NABORLAR (5 товаров)
    {
        id: 36,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kastrulka Nabor 1',
        price: 320000,
        newPrice: 300000,
        discount: true,
        category: 'KASTRULKA NABORLAR',
        rating: { rate: 4.3, count: 68 },
        shortDesc: 'Kastrulka va qo‘shimcha aksessuarlar nabori.',
        fullDesc: 'Bitta naborda turli o‘lchamdagi kastrulkalar va qo‘shimcha asboblar.',
        weight: '2.2kg',
        color: 'ko‘k',
        type: 'komplekt',
        qty: 55,
        tages: 'kastrulka nabor, oshxona, komplekt',
        brandImg: '/images/brands/brand8.png',
        comments: [
            { clientName: 'Ali', clientComment: 'Yaxshi nabor, hamma kerakli narsalar bor.', clientRate: 5 },
        ],
        sku: 'KSNB-001',
    },
    {
        id: 37,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kastrulka Nabor 2',
        price: 340000,
        newPrice: 340000,
        discount: false,
        category: 'KASTRULKA NABORLAR',
        rating: { rate: 4.0, count: 60 },
        shortDesc: 'Standart nabor kastrulkalar.',
        fullDesc: 'Sodda va qulay, kundalik pishirish uchun ideal variant.',
        weight: '2.0kg',
        color: 'qizil',
        type: 'standart',
        qty: 60,
        tages: 'kastrulka nabor, standart, oshxona',
        brandImg: '/images/brands/brand8.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Oddiy, lekin ishlaydi.', clientRate: 4 },
        ],
        sku: 'KSNB-002',
    },
    {
        id: 38,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kastrulka Nabor Deluxe',
        price: 380000,
        newPrice: 350000,
        discount: true,
        category: 'KASTRULKA NABORLAR',
        rating: { rate: 4.6, count: 80 },
        shortDesc: 'Deluxe nabor, yuqori sifat kafolati.',
        fullDesc: 'Yuqori darajadagi materiallar va innovatsion dizayn.',
        weight: '2.5kg',
        color: 'oltin',
        type: 'deluxe',
        qty: 45,
        tages: 'kastrulka nabor, deluxe, oshxona',
        brandImg: '/images/brands/brand8.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Kuchli nabor, tavsiya qilaman!', clientRate: 5 },
        ],
        sku: 'KSNB-003',
    },
    {
        id: 39,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kastrulka Nabor Basic',
        price: 300000,
        newPrice: 300000,
        discount: false,
        category: 'KASTRULKA NABORLAR',
        rating: { rate: 3.9, count: 55 },
        shortDesc: 'Asosiy nabor, kundalik pishirish uchun.',
        fullDesc: 'Oddiy dizayn, lekin hamma kerakli aksessuarlarni o‘z ichiga oladi.',
        weight: '2.1kg',
        color: 'kulrang',
        type: 'basic',
        qty: 65,
        tages: 'kastrulka nabor, basic, oshxona',
        brandImg: '/images/brands/brand8.png',
        comments: [
            { clientName: 'Jasur', clientComment: 'Narxi arzon, foydali.', clientRate: 4 },
        ],
        sku: 'KSNB-004',
    },
    {
        id: 40,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kastrulka Nabor Pro',
        price: 400000,
        newPrice: 400000,
        discount: false,
        category: 'KASTRULKA NABORLAR',
        rating: { rate: 4.2, count: 62 },
        shortDesc: 'Professional nabor, oshpazlar uchun mo‘ljallangan.',
        fullDesc: 'Kuchli va bardoshli nabor, yuqori texnologiya bilan ta’minlangan.',
        weight: '2.3kg',
        color: 'ko‘k',
        type: 'pro',
        qty: 50,
        tages: 'kastrulka nabor, pro, oshxona',
        brandImg: '/images/brands/brand8.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Hamma narsa bir joyda, juda qulay.', clientRate: 5 },
        ],
        sku: 'KSNB-005',
    },
    // KICHIK TURDAGI MAISHIY TEXNIKALAR (5 товаров)
    {
        id: 41,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Mini Blender',
        price: 100000,
        newPrice: 90000,
        discount: true,
        category: 'KICHIK TURDAGI MAISHIY TEXNIKALAR',
        rating: { rate: 4.1, count: 70 },
        shortDesc: 'Kichik o‘lchamli, lekin kuchli blender.',
        fullDesc: 'Kichik va kompakt dizayn, idishlarni aralashtirish uchun yetarli kuchga ega.',
        weight: '1kg',
        color: 'qora',
        type: 'elektron',
        qty: 80,
        tages: 'blender, kichik, oshxona',
        brandImg: '/images/brands/brand9.png',
        comments: [
            { clientName: 'Ali', clientComment: 'Sodda va ishni yaxshi bajaradi.', clientRate: 4 },
        ],
        sku: 'MTX-001',
    },
    {
        id: 42,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kichik Mikser',
        price: 85000,
        newPrice: 85000,
        discount: false,
        category: 'KICHIK TURDAGI MAISHIY TEXNIKALAR',
        rating: { rate: 3.9, count: 50 },
        shortDesc: 'Kichik hajmli, lekin samarali mikser.',
        fullDesc: 'Arzon va ishonchli, kundalik foydalanish uchun mos.',
        weight: '0.9kg',
        color: 'oq',
        type: 'elektron',
        qty: 90,
        tages: 'mikser, kichik, oshxona',
        brandImg: '/images/brands/brand9.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Oddiy mikser, lekin ishonchli.', clientRate: 4 },
        ],
        sku: 'MTX-002',
    },
    {
        id: 43,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Mini Toaster',
        price: 75000,
        newPrice: 75000,
        discount: false,
        category: 'KICHIK TURDAGI MAISHIY TEXNIKALAR',
        rating: { rate: 4.0, count: 55 },
        shortDesc: 'Kichik va tejamkor toaster.',
        fullDesc: 'Nonni qizdirishda samarali va kompakt dizayn.',
        weight: '0.8kg',
        color: 'qizil',
        type: 'elektron',
        qty: 100,
        tages: 'toaster, kichik, oshxona',
        brandImg: '/images/brands/brand9.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Oddiy, lekin samarali ishlaydi.', clientRate: 4 },
        ],
        sku: 'MTX-003',
    },
    {
        id: 44,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Mini Mikrotolqinli',
        price: 200000,
        newPrice: 200000,
        discount: false,
        category: 'KICHIK TURDAGI MAISHIY TEXNIKALAR',
        rating: { rate: 4.2, count: 65 },
        shortDesc: 'Kichik, lekin kuchli mikrotolqinli pech.',
        fullDesc: 'Tez qiziydigan va energiyani tejovchi texnologiya bilan.',
        weight: '12kg',
        color: 'kulrang',
        type: 'elektron',
        qty: 30,
        tages: 'mikrotolqin, kichik, oshxona',
        brandImg: '/images/brands/brand9.png',
        comments: [
            { clientName: 'Jasur', clientComment: 'Kichik joylarda ajoyib yechim.', clientRate: 5 },
        ],
        sku: 'MTX-004',
    },
    {
        id: 45,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Kichik Qahva Mashinasi',
        price: 300000,
        newPrice: 280000,
        discount: true,
        category: 'KICHIK TURDAGI MAISHIY TEXNIKALAR',
        rating: { rate: 4.3, count: 70 },
        shortDesc: 'Kichik, lekin samarali qahva mashinasi.',
        fullDesc: 'Tez tayyorlanadigan va kompakt dizaynga ega, ofis va uy uchun mos.',
        weight: '2kg',
        color: 'qora',
        type: 'elektron',
        qty: 40,
        tages: 'qahva, kichik, oshxona',
        brandImg: '/images/brands/brand9.png',
        comments: [
            { clientName: 'Ali', clientComment: 'Sifatli, lekin biroz shovqinli.', clientRate: 4 },
        ],
        sku: 'MTX-005',
    },
    // MANTIQASQONLAR (5 товаров)
    {
        id: 46,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Mantiqasqon Set 1',
        price: 180000,
        newPrice: 160000,
        discount: true,
        category: 'MANTIQASQONLAR',
        rating: { rate: 4.0, count: 50 },
        shortDesc: 'Oddiy mantiqasqon to‘plami.',
        fullDesc: 'Kundalik foydalanish uchun yetarli, oddiy dizayn.',
        weight: '0.6kg',
        color: 'oq',
        type: 'plastik',
        qty: 90,
        tages: 'mantiqasqon, oshxona, set',
        brandImg: '/images/brands/brand10.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Oddiy, lekin yaxshi ishlaydi.', clientRate: 4 },
        ],
        sku: 'MNT-001',
    },
    {
        id: 47,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Mantiqasqon Set 2',
        price: 200000,
        newPrice: 200000,
        discount: false,
        category: 'MANTIQASQONLAR',
        rating: { rate: 4.2, count: 60 },
        shortDesc: 'Standart mantiqasqon to‘plami.',
        fullDesc: 'Kundalik foydalanish uchun mo‘ljallangan, qulay dizaynli.',
        weight: '0.7kg',
        color: 'qizil',
        type: 'standart',
        qty: 85,
        tages: 'mantiqasqon, standart, oshxona',
        brandImg: '/images/brands/brand10.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Oddiy va qulay, tavsiya etaman.', clientRate: 4 },
        ],
        sku: 'MNT-002',
    },
    {
        id: 48,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Mantiqasqon Set Deluxe',
        price: 250000,
        newPrice: 230000,
        discount: true,
        category: 'MANTIQASQONLAR',
        rating: { rate: 4.5, count: 70 },
        shortDesc: 'Deluxe mantiqasqon to‘plami.',
        fullDesc: 'Yuqori sifatli materiallar bilan tayyorlangan, nafis dizaynga ega.',
        weight: '0.8kg',
        color: 'ko‘k',
        type: 'deluxe',
        qty: 75,
        tages: 'mantiqasqon, deluxe, oshxona',
        brandImg: '/images/brands/brand10.png',
        comments: [
            { clientName: 'Jasur', clientComment: 'Haqiqiy deluxe, tavsiya etaman!', clientRate: 5 },
        ],
        sku: 'MNT-003',
    },
    {
        id: 49,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Mantiqasqon Standart',
        price: 170000,
        newPrice: 170000,
        discount: false,
        category: 'MANTIQASQONLAR',
        rating: { rate: 3.9, count: 45 },
        shortDesc: 'Arzon va oddiy mantiqasqon seti.',
        fullDesc: 'Kundalik foydalanish uchun oddiy dizaynga ega, narxi ma’qul.',
        weight: '0.6kg',
        color: 'kulrang',
        type: 'basic',
        qty: 95,
        tages: 'mantiqasqon, basic, oshxona',
        brandImg: '/images/brands/brand10.png',
        comments: [
            { clientName: 'Ali', clientComment: 'Oddiy va ishonchli.', clientRate: 4 },
        ],
        sku: 'MNT-004',
    },
    {
        id: 50,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Mantiqasqon Pro',
        price: 280000,
        newPrice: 280000,
        discount: false,
        category: 'MANTIQASQONLAR',
        rating: { rate: 4.3, count: 55 },
        shortDesc: 'Pro mantiqasqon to‘plami, mustahkam va chidamli.',
        fullDesc: 'Zamonaviy dizayn va yuqori texnologiyali ishlab chiqarish.',
        weight: '0.9kg',
        color: 'qora',
        type: 'pro',
        qty: 60,
        tages: 'mantiqasqon, pro, oshxona',
        brandImg: '/images/brands/brand10.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Ajoyib mahsulot, tavsiya qilaman.', clientRate: 5 },
        ],
        sku: 'MNT-005',
    },
    // BLINITSALAR (5 товаров)
    {
        id: 51,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Blinitsa Klassik',
        price: 110000,
        newPrice: 110000,
        discount: false,
        category: 'BLINITSALAR',
        rating: { rate: 4.2, count: 80 },
        shortDesc: 'Klassik blinitsa retsepti bo‘yicha.',
        fullDesc: 'Oddiy, lekin mazali blinitsa uchun eng zo‘r tanlov.',
        weight: '0.5kg',
        color: 'oq',
        type: 'klassik',
        qty: 120,
        tages: 'blinitsa, klassik, oshxona',
        brandImg: '/images/brands/brand11.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Sodda va mazali, retseptga mos.', clientRate: 4 },
        ],
        sku: 'BLN-001',
    },
    {
        id: 52,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Blinitsa Deluxe',
        price: 150000,
        newPrice: 135000,
        discount: true,
        category: 'BLINITSALAR',
        rating: { rate: 4.5, count: 90 },
        shortDesc: 'Deluxe blinitsa, nozik va yumshoq.',
        fullDesc: 'Yuqori sifatli ingredientlar bilan tayyorlangan, blinitsa san’ati.',
        weight: '0.6kg',
        color: 'qizil',
        type: 'deluxe',
        qty: 100,
        tages: 'blinitsa, deluxe, oshxona',
        brandImg: '/images/brands/brand11.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Noyob ta’m, haqiqiy delux hissi beradi.', clientRate: 5 },
        ],
        sku: 'BLN-002',
    },
    {
        id: 53,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Blinitsa Express',
        price: 90000,
        newPrice: 90000,
        discount: false,
        category: 'BLINITSALAR',
        rating: { rate: 3.8, count: 50 },
        shortDesc: 'Tez tayyorlanadigan blinitsa.',
        fullDesc: 'Qisqa vaqt ichida pishiriladigan va mazali natija beradi.',
        weight: '0.5kg',
        color: 'kulrang',
        type: 'express',
        qty: 130,
        tages: 'blinitsa, express, oshxona',
        brandImg: '/images/brands/brand11.png',
        comments: [
            { clientName: 'Jasur', clientComment: 'Oddiy, lekin tez tayyorlanadi.', clientRate: 4 },
        ],
        sku: 'BLN-003',
    },
    {
        id: 54,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Blinitsa Set',
        price: 130000,
        newPrice: 130000,
        discount: false,
        category: 'BLINITSALAR',
        rating: { rate: 4.0, count: 65 },
        shortDesc: 'To‘plamda turli xil blinitsalar.',
        fullDesc: 'Oila uchun bir nechta variantda blinitsalar, har birining o‘ziga xos ta’mi bor.',
        weight: '1kg',
        color: 'oq',
        type: 'set',
        qty: 110,
        tages: 'blinitsa, set, oshxona',
        brandImg: '/images/brands/brand11.png',
        comments: [
            { clientName: 'Olim', clientComment: 'Ajoyib to‘plam, oilaviy uchrashuv uchun ideal.', clientRate: 5 },
        ],
        sku: 'BLN-004',
    },
    {
        id: 55,
        images: [
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
            '/images/prodImg.png',
        ],
        name: 'Blinitsa Classic Set',
        price: 140000,
        newPrice: 125000,
        discount: true,
        category: 'BLINITSALAR',
        rating: { rate: 4.3, count: 70 },
        shortDesc: 'Klassik blinitsa to‘plami.',
        fullDesc: 'Klassik retsept asosida tayyorlangan, har doim mazali natija beradi.',
        weight: '0.7kg',
        color: 'qora',
        type: 'classic',
        qty: 105,
        tages: 'blinitsa, classic, oshxona',
        brandImg: '/images/brands/brand11.png',
        comments: [
            { clientName: 'Madina', clientComment: 'Haqiqiy klassika, har doim yoqadi.', clientRate: 5 },
        ],
        sku: 'BLN-005',
    },
];